#!/usr/bin/env bash
if [ -f /usr/bin/gcc ]
then
    echo "gcc exists"
else
  "echo go get GCC! and try again"
  open https://github.com/kennethreitz/osx-gcc-installer
  exit
fi

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.bash_profile
  source ~/.bash_profile

echo "Installing Mysql, a good open source relational database ..."
  
  brew install mysql
  mkdir -p ~/Library/LaunchAgents
  launchctl unload -w ~/Library/LaunchAgents/com.mysql.mysqld.plist
  cp /usr/local/Cellar/mysql/`brew info mysql | sed -n 1p | awk '{ print $2}'`/com.mysql.mysqld.plist ~/Library/LaunchAgents/
  launchctl load -w ~/Library/LaunchAgents/com.mysql.mysqld.plist
  
echo "Installing Redis, a good key-value database ..."
  brew install redis
  launchctl unload -w ~/Library/LaunchAgents/io.redis.redis-server.plist
  cp /usr/local/Cellar/redis/`brew info redis | sed -n 1p | awk '{ print $2}'`/io.redis.redis-server.plist ~/Library/LaunchAgents/
  launchctl load -w ~/Library/LaunchAgents/io.redis.redis-server.plist

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "installing Git, cus you'll need it"
  brew install git
  
echo "installing php. we use it. sometimes. look, i'm not proud of it either."
  brew install https://raw.github.com/adamv/homebrew-alt/raw/master/duplicates/php.rb --with-mysql --with-fpm
  echo 'export PATH='`brew --prefix php`'/bin:$PATH' >> .bash_profile


# echo "Installing tmux, a good way to save project state and switch between projects ..."
#   brew install tmux
# 
# echo "Installing ImageMagick, good for cropping and re-sizing images ..."
#   brew install imagemagick

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.bashrc
  source ~/.bash_profile

  echo "gem: --no-ri --no-rdoc" >>~/.gemrc
  echo "require 'rubygems'
  require 'pp'
  require 'wirble'
  Wirble.init
  Wirble.colorize
  IRB.conf[:AUTO_INDENT] = true
  IRB.conf[:USE_READLINE] = true
  IRB.conf[:LOAD_MODULES] = [] unless IRB.conf.key?(:LOAD_MODULES)
  unless IRB.conf[:LOAD_MODULES].include?('irb/completion')
    IRB.conf[:LOAD_MODULES] << 'irb/completion'
  end " >> ~/.irbrc
 echo "starting the ruby setup"
bash < <(curl -s https://raw.github.com/Headlinerfm/laptop/master/ruby)
